version: '3.8'

services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: sca
        POSTGRES_PASSWORD: root
        POSTGRES_DB: sca
      ports:
        - "5232:5432"